import postgres from 'postgres'

const DATABASE_URL = 'postgresql://neondb_owner:npg_KMCUPT9u6RQj@ep-tiny-salad-aluubdyp-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require'
const sql = postgres(DATABASE_URL, { ssl: 'require' })

const products = [
  {
    id: 'me-preworkout-ultra',
    name: 'ME PRE-WORKOUT ULTRA',
    tagline: 'Explosive energy, laser focus, unstoppable power',
    description: 'The most advanced pre-workout formula ever created. Engineered with 350mg caffeine, 6g L-Citrulline, and our proprietary NeuroFocus™ blend for skin-tingling pumps, tunnel vision focus, and energy that lasts the entire session.',
    price: 54.99, original_price: 69.99,
    category: 'pre-workout', category_label: 'Pre-Workout',
    badge: 'BESTSELLER', badge_color: 'neon-pink',
    rating: 4.9, reviews: 2847, stock: 94, servings: 30,
    flavours: ['Galaxy Punch', 'Neon Watermelon', 'Cosmic Berry', 'Electric Lemon'],
    sizes: ['300g', '600g'],
    key_benefits: ['350mg Caffeine Anhydrous', '6g L-Citrulline Malate', '3.2g Beta-Alanine', 'Electrolyte Matrix', 'Zero Sugar'],
    ingredients: 'L-Citrulline Malate, Beta-Alanine, Caffeine Anhydrous, L-Tyrosine, Alpha GPC, Betaine Anhydrous, Electrolyte Blend',
    emoji: '⚡', gradient: 'from-neon-purple via-neon-pink to-neon-orange', accent_color: '#b026ff',
    featured: true, bestseller: true, new_arrival: false,
  },
  {
    id: 'me-whey-protein',
    name: 'ME WHEY PROTEIN X',
    tagline: 'Pure performance protein, every scoop',
    description: 'Ultra-premium whey protein isolate with 27g of protein per serving, virtually zero fat and carbs. Cold-processed to preserve bioactive fractions, delivering rapid amino acid uptake for maximum muscle protein synthesis.',
    price: 64.99, original_price: 79.99,
    category: 'protein', category_label: 'Protein',
    badge: 'NEW FLAVOUR', badge_color: 'neon-cyan',
    rating: 4.8, reviews: 1923, stock: 67, servings: 30,
    flavours: ['Neon Chocolate', 'Vanilla Circuit', 'Strawberry Surge', 'Peanut Butter Pixel', 'Cookies & Circuits'],
    sizes: ['900g', '2kg', '4.5kg'],
    key_benefits: ['27g Protein Per Serving', 'Whey Isolate 90%', '<1g Fat', '<2g Carbs', 'Digestive Enzymes Included'],
    ingredients: 'Whey Protein Isolate (Milk), Cocoa Powder, Natural Flavours, Sunflower Lecithin, Sucralose, Digestive Enzyme Blend',
    emoji: '💪', gradient: 'from-neon-cyan via-neon-purple to-neon-pink', accent_color: '#00f5ff',
    featured: true, bestseller: true, new_arrival: false,
  },
  {
    id: 'me-creatine-mono',
    name: 'ME CREATINE MONO+',
    tagline: 'Pharmaceutical-grade power amplifier',
    description: 'Creapure® certified creatine monohydrate — the gold standard for strength, power, and muscle volumization. Micronized for maximum solubility and absorption.',
    price: 29.99, original_price: null,
    category: 'creatine', category_label: 'Creatine',
    badge: 'PURE FORMULA', badge_color: 'neon-green',
    rating: 4.9, reviews: 4201, stock: 142, servings: 60,
    flavours: ['Unflavoured', 'Blue Raspberry'],
    sizes: ['300g', '500g', '1kg'],
    key_benefits: ['5g Creapure® Per Serving', 'Micronized Formula', '100% Pure', 'No Fillers', 'Mixes Instantly'],
    ingredients: 'Creatine Monohydrate (Creapure®)',
    emoji: '🔥', gradient: 'from-neon-green via-neon-cyan to-neon-purple', accent_color: '#39ff14',
    featured: true, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-energy-drink-bundle',
    name: 'ME ENERGY RTD PACK',
    tagline: 'Ready-to-destroy. Ready-to-drink.',
    description: 'Our flagship ready-to-drink energy formula. 200mg natural caffeine, adaptogens, B-vitamins, and electrolytes in a carbonated neon blast. Zero sugar, zero compromise.',
    price: 39.99, original_price: 49.99,
    category: 'energy', category_label: 'Energy Drinks',
    badge: '12-PACK', badge_color: 'neon-orange',
    rating: 4.7, reviews: 3102, stock: 55, servings: 12,
    flavours: ['Neon Watermelon', 'Electric Mango', 'Cosmic Berry', 'Galaxy Punch', 'Phantom Grape'],
    sizes: ['12x330ml'],
    key_benefits: ['200mg Natural Caffeine', 'Zero Sugar', 'B-Vitamin Complex', 'Electrolytes', 'Adaptogens'],
    ingredients: 'Carbonated Water, Taurine, Natural Caffeine, B3, B6, B12, Sodium, Potassium, Ashwagandha Extract',
    emoji: '🌊', gradient: 'from-neon-orange via-neon-pink to-neon-purple', accent_color: '#ff6600',
    featured: true, bestseller: true, new_arrival: false,
  },
  {
    id: 'me-bcaa-matrix',
    name: 'ME BCAA MATRIX',
    tagline: 'Anti-catabolic fuel for non-stop training',
    description: 'Advanced 2:1:1 BCAA formula with added L-Glutamine, Coconut Water powder, and our HydraFuel™ electrolyte blend.',
    price: 39.99, original_price: 44.99,
    category: 'recovery', category_label: 'BCAAs & Recovery',
    badge: null, badge_color: null,
    rating: 4.7, reviews: 1456, stock: 88, servings: 30,
    flavours: ['Pink Lemonade', 'Blue Raspberry', 'Watermelon Wave', 'Peach Rings'],
    sizes: ['300g', '600g'],
    key_benefits: ['10g BCAAs 2:1:1', '5g L-Glutamine', 'Coconut Water Powder', 'Zero Calories', 'Intra or Post-Workout'],
    ingredients: 'L-Leucine, L-Isoleucine, L-Valine, L-Glutamine, Coconut Water Powder, Electrolyte Blend, Vitamin B6',
    emoji: '🧬', gradient: 'from-neon-pink via-neon-purple to-neon-cyan', accent_color: '#ff2d78',
    featured: false, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-fat-burner-thermo',
    name: 'ME THERMO IGNITE',
    tagline: 'Melt fat. Keep muscle. Stay electric.',
    description: 'Multi-stage thermogenic fat burner engineered for elite body recomposition. Combines 250mg caffeine, Capsimax®, Green Tea extract, L-Carnitine, and CLA.',
    price: 49.99, original_price: 59.99,
    category: 'fat-burner', category_label: 'Fat Burners',
    badge: 'HOT', badge_color: 'neon-orange',
    rating: 4.6, reviews: 987, stock: 43, servings: 30,
    flavours: ['Capsule — 90 caps'],
    sizes: ['90 Capsules'],
    key_benefits: ['250mg Caffeine Complex', 'Capsimax® Cayenne', 'Green Tea EGCG', 'L-Carnitine 1000mg', 'CLA 500mg'],
    ingredients: 'Caffeine Anhydrous, Green Tea Extract, L-Carnitine Tartrate, Capsimax®, CLA, BioPerine®',
    emoji: '💥', gradient: 'from-neon-orange via-neon-pink to-neon-purple', accent_color: '#ff6600',
    featured: false, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-hydration-pack',
    name: 'ME HYDRAX ELITE',
    tagline: 'Total hydration, maximum performance',
    description: 'Hospital-grade electrolyte hydration formula with an advanced mineral matrix. Coconut water, sea minerals, and our PureSalt™ blend.',
    price: 34.99, original_price: null,
    category: 'hydration', category_label: 'Hydration',
    badge: 'NEW', badge_color: 'neon-cyan',
    rating: 4.8, reviews: 612, stock: 71, servings: 30,
    flavours: ['Lemon Volt', 'Tropical Circuit', 'Watermelon Static', 'Mango Surge'],
    sizes: ['270g', '540g'],
    key_benefits: ['1000mg Sodium', '500mg Potassium', 'Coconut Water Powder', 'Sea Minerals', 'Zero Caffeine'],
    ingredients: 'Sodium Citrate, Potassium Chloride, Magnesium Glycinate, Calcium Lactate, Coconut Water Powder, Sea Mineral Complex, Vitamin C',
    emoji: '💧', gradient: 'from-neon-cyan via-neon-green to-neon-purple', accent_color: '#00f5ff',
    featured: false, bestseller: false, new_arrival: true,
  },
  {
    id: 'me-mass-gainer',
    name: 'ME MASS REACTOR',
    tagline: 'Hard gainer no more. Build serious size.',
    description: 'The ultimate high-calorie, high-protein mass gainer. 1250 calories, 50g protein, and 250g complex carbs per serving.',
    price: 74.99, original_price: 89.99,
    category: 'protein', category_label: 'Mass Gainers',
    badge: null, badge_color: null,
    rating: 4.6, reviews: 834, stock: 29, servings: 14,
    flavours: ['Triple Chocolate', 'Vanilla Overdrive', 'Strawberry Bomb'],
    sizes: ['3kg', '6kg'],
    key_benefits: ['1250 Calories', '50g Protein', '250g Carbohydrates', 'Creatine Included', 'Added MCTs'],
    ingredients: 'Maltodextrin, Oat Flour, Whey Protein Concentrate, Micellar Casein, Creatine Monohydrate, MCT Oil, Digestive Enzyme Blend',
    emoji: '🏋️', gradient: 'from-neon-purple via-neon-pink to-neon-orange', accent_color: '#b026ff',
    featured: false, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-omega-3',
    name: 'ME OMEGA ULTRA 3X',
    tagline: 'Premium fish oil for peak performance & recovery',
    description: 'Triple-strength concentrated fish oil from sustainably sourced wild-caught fish. 3000mg Omega-3 per serving with 1500mg EPA and 1000mg DHA.',
    price: 24.99, original_price: null,
    category: 'recovery', category_label: 'Wellness',
    badge: null, badge_color: null,
    rating: 4.8, reviews: 2234, stock: 115, servings: 30,
    flavours: ['Capsule — Enteric Coated'],
    sizes: ['90 Softgels', '180 Softgels'],
    key_benefits: ['3000mg Omega-3', '1500mg EPA', '1000mg DHA', 'Enteric-Coated', 'Sustainably Sourced'],
    ingredients: 'Fish Oil Concentrate (Anchovy, Sardine), EPA, DHA, Vitamin E, Gelatin',
    emoji: '🐟', gradient: 'from-neon-cyan via-neon-purple to-neon-pink', accent_color: '#00f5ff',
    featured: false, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-starter-stack',
    name: 'ME STARTER STACK',
    tagline: 'Everything you need to start your journey',
    description: 'The perfect beginner bundle: Pre-Workout Ultra + Whey Protein X + Creatine Mono+. Save 33% vs buying separately. Full 8-week transformation stack.',
    price: 99.99, original_price: 149.97,
    category: 'pre-workout', category_label: 'Bundles',
    badge: 'SAVE 33%', badge_color: 'neon-green',
    rating: 4.9, reviews: 567, stock: 22, servings: 120,
    flavours: ['Mixed Pack'],
    sizes: ['Bundle'],
    key_benefits: ['Pre-Workout + Protein + Creatine', '8-Week Supply', 'Save R50', 'Free Shaker', 'Nutrition Guide Included'],
    ingredients: 'See individual products for full ingredient lists',
    emoji: '🚀', gradient: 'from-neon-green via-neon-cyan to-neon-purple', accent_color: '#39ff14',
    featured: true, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-sleep-recovery',
    name: 'ME SLEEP & RECOVER',
    tagline: 'Grow while you sleep. Wake up ready.',
    description: 'Nighttime anabolic recovery formula. Magnesium Glycinate, ZMA, Ashwagandha, Melatonin, and Casein Protein for deeper sleep and overnight recovery.',
    price: 44.99, original_price: null,
    category: 'recovery', category_label: 'Recovery',
    badge: 'NIGHTTIME', badge_color: 'neon-purple',
    rating: 4.7, reviews: 1103, stock: 58, servings: 30,
    flavours: ['Night Berry', 'Chamomile Dream', 'Unflavoured'],
    sizes: ['270g', '30 Servings'],
    key_benefits: ['Magnesium Glycinate 400mg', 'ZMA Complex', 'Ashwagandha 600mg KSM-66', '3mg Melatonin', '20g Micellar Casein'],
    ingredients: 'Micellar Casein, Magnesium Glycinate, Zinc Citrate, Vitamin B6, KSM-66 Ashwagandha, Melatonin, L-Theanine',
    emoji: '🌙', gradient: 'from-neon-purple via-dark-700 to-neon-cyan', accent_color: '#b026ff',
    featured: false, bestseller: false, new_arrival: false,
  },
  {
    id: 'me-multivitamin',
    name: 'ME MULTI PERFORMANCE',
    tagline: 'The foundation every serious athlete needs',
    description: 'Comprehensive sport-specific multivitamin with 30+ micronutrients, antioxidants, and immune-support compounds optimized for athletes.',
    price: 19.99, original_price: null,
    category: 'recovery', category_label: 'Vitamins & Minerals',
    badge: null, badge_color: null,
    rating: 4.7, reviews: 1876, stock: 200, servings: 30,
    flavours: ['Tablet — 2 per day'],
    sizes: ['60 Tablets', '120 Tablets'],
    key_benefits: ['30+ Micronutrients', 'CoQ10 & Lutein', 'Adaptogen Complex', 'Immune Support', 'No Artificial Colours'],
    ingredients: 'Vitamin A, C, D3, E, K2, B-Complex, Iron, Zinc, Selenium, Magnesium, CoQ10, Lutein, Lycopene, Ashwagandha, Rhodiola',
    emoji: '💊', gradient: 'from-neon-yellow via-neon-green to-neon-cyan', accent_color: '#ffe600',
    featured: false, bestseller: false, new_arrival: false,
  },
]

async function seed() {
  console.log('🌱 Seeding products...')

  // Clear existing products first
  await sql`DELETE FROM products`

  for (const p of products) {
    await sql`
      INSERT INTO products (
        id, name, tagline, description, price, original_price,
        category, category_label, badge, badge_color,
        rating, reviews, stock, servings,
        flavours, sizes, key_benefits, ingredients,
        emoji, gradient, accent_color,
        featured, bestseller, new_arrival
      ) VALUES (
        ${p.id}, ${p.name}, ${p.tagline}, ${p.description},
        ${p.price}, ${p.original_price},
        ${p.category}, ${p.category_label}, ${p.badge}, ${p.badge_color},
        ${p.rating}, ${p.reviews}, ${p.stock}, ${p.servings},
        ${JSON.stringify(p.flavours)}, ${JSON.stringify(p.sizes)},
        ${JSON.stringify(p.key_benefits)}, ${p.ingredients},
        ${p.emoji}, ${p.gradient}, ${p.accent_color},
        ${p.featured}, ${p.bestseller}, ${p.new_arrival}
      )
    `
    console.log(`  ✅ ${p.name}`)
  }

  await sql.end()
  console.log(`\n🎉 Seeded ${products.length} products successfully!`)
}

seed().catch((e) => { console.error('Seed failed:', e); process.exit(1) })
